matrix:
  include:
    - language: python
      dist: xenial
      python: 3.7
      before_script:
        - pip install -r backend/requirements/development.txt
      script:
        - black -l 79 --check backend/
        - flake8
        - pytest backend/
