const path = require("path");
const fs = require("fs");

/*
 * This Plugin allows the compilation of all the Levels and the injection of
 * them into the game.
 */

// Set the installed levels directory
const directoryPath = path.join(__dirname, path.join("src", "levels"));

class LevelLoaderPlugin {
  apply(compiler) {
    compiler.hooks.beforeCompile.tap(
      "LevelLoaderPlugin",
      (compilation, callback) => {
        fs.readdir(directoryPath, (err, files) => {
          if (err) console.log("Error accessing to Levels folder");
          else {
            let levelsLoader_content = `
/*
* Autogenerated file during compilation.
* Do not override.
* 
*/\n\n`;
            let levelsImport = "";
            let levelsList = "\ninstalled_levels = [\n";
            let exports = "export default installed_levels;\n";

            files.forEach(folder => {
              levelsImport += `const ${folder}Level = require("./levels/${folder}");\n`;
              levelsList += `    ${folder}Level,\n`;
            });
            levelsList += "]\n";

            levelsLoader_content += levelsImport + levelsList + exports;

            fs.writeFile("src/level_loader.js", levelsLoader_content, err => {
              if (err) throw err;
              console.log("[+] Levels registered");
            });
          }
        });
      }
    );
  }
}

module.exports = LevelLoaderPlugin;
